# Introduction to Vectors

## Definition

Representing an n-dimensional vector requests to offer an n-dimensional vector space $\mathbb{V}^n$. The vector is written as an n-tuple of numbers. For n-dimensional real vector space $\mathbb{R}^n = \{(r_1, r_2, ... , r_n): r_1, r_2, ... , r_n \in \mathbb{R}^n \}$, the vector can be represented as $\vec{r} = (r_1, r_2, ... , r_n) $

For example, the vector $\vec{r} = (x, y, z)$ is a 3-dimensional vector in $\mathbb{R}^3$. The zero vector is in $\mathbb{R}^n$ with all elements zero.

Vectors can be divided into row vectors and column vectors. The transpose of a column vector is a row vector with the same length and elements order, and vice versa. The transpose of vector $v$ is represented as $v^T$, the conjugate of this vector is represented as $v^*$, and the Hermitian transpose (conjugate transpose) is represented as $v^\dag$. With Dirac notation, we can represent a row vector as a Bra: $|r⟩$, and a column vector as a Ket: $⟨c|$.

The vector $|v⟩$ and $⟨v|$ are transposed conjugate to each other:

$$  \left\{\begin{array}{rcl}
    a|v⟩ =  a^*⟨v|^\dag \\
    a⟨v| =  a^*|v⟩^\dag
\end{array}\right. $$

In Python, with the package `NumPy`, we can use the function `numpy.array` to represent a vector.

We will respectively demonstrate a row vector $⟨r|$ and a column vector $|c⟩$ as follows.


In [28]:
import numpy as np

v = np.array([1.2,2.3,3.1]); v

array([1.2, 2.3, 3.1])

In [29]:
u = np.array([[1.1],[2.2],[3.3]]); u

array([[1.1],
       [2.2],
       [3.3]])

### Indexing

A specific element of vector $x[i]$ can be extracted with the expression `x[i]`, it should be noticed that the index $i$ starts from $0$.

In [30]:
v[1]

2.3

The element can be revised if it is on the left-hand side of an assignment statement.

In [31]:
v[1] = 2.21
v[1]

2.21

### Norm

The norm of a vector is a function from a real or complex vector space to the non-negative real numbers. The most common concept of a norm is the Euclidean norm. The Euclidean norm of a vector is the measure of its length, it is also called $L^2$ norm, $\ell^2$ norm, or square norm, it can be denoted by $\|v\|_2$, this length is called Euclidean length, $L^2$ length, or $\ell^2$ length which refers to the Physical length:

$$ \|v\|_2 = \sqrt{\sum_i v_i^2} $$

The package `NumPy` provides the function `numpy.linalg.norm` to compute the Euclidean and Manhattan norm:

In [32]:
v = np.array([[1.4, 2.3, 3.2, 4.1]]);

np.linalg.norm(v, 2)

5.856620185738529

The default value of this function refers to the Euclidean norm:

In [33]:
np.linalg.norm(v)

5.856620185738529

For a complex number $z = x + iy $, its Euclidean norm equals its absolute value: the sqrt of the dot product with itself:

$$ \|z\|= |z| = \sqrt{x^2 + y^2} = \sqrt{z \cdot z^*} $$

In addition, for a vector $v$, the Manhattan norm (or Taxicab norm) is written as $\|v\|_1$ and measures the sum of the absolute differences of the Cartesian coordinates of its elements: the Manhattan distance Manhattan norm can be called $L^1$ norm or $\ell^1$ norm, the Manhattan distance can be also called $L^1$ distance or $\ell^1$ distance.

For a vector $v$, the Manhattan norm is demonstrated as:

$$ \|\vec{v}\|_1 = \sum_i v_i $$

For a 2-dimensional vector $\vec{d}(x,y)$, its Manhattan norm is computed as:

$$ \|\vec{d}(x,y)\|_1 = |x|+|y| $$

The following code will compute the Manhattan norm of a vector:

In [34]:
np.linalg.norm(v, 1)

4.1

The absolute-value norm works on one-dimensional vector spaces formed by real or complex numbers. For a complex number, its absolute-value norm equals its Euclidean norm.

### Vector multiplication

The vector multiplication is the product of a vector and a scalar: 

$$ a|v⟩ = (av_1, av_2, ..., av_n) $$

It obeys the linear property:

Commutative law:

$$ a|v⟩ = |v⟩a $$

Associative law:

$$ (a\cdot b)|v⟩ = a(b|v⟩) $$

Distributive law:

$$ (a + b)|v⟩ = a|v⟩ + b|v⟩ $$


### Dot product

Both dot product and cross product requires the acting vectors to have the same length. For the vectors: $\vec u$ and $\vec v$, the dot product of them is the sum of the product of the respective elements in each vector. It is denoted by $\vec u \cdot \vec v$, or $⟨u|v⟩$ in Dirac notation:

$$ \vec u \cdot \vec v = ⟨u|v⟩ =  \sum_{i} u_i v_i $$

We introduce the angle between two vectors: $\theta$, the dot product can be demonstrated as:

$$ \vec u \cdot \vec v = \|u\|_2\|v\|_2\cos{\theta} $$

The following code finds the angle between two vectors:

In [35]:
u = np.array([[3.21, 1.32 , 2.13]])

v = np.array([[1.11],[2.22],[3.33]])

np.arccos(np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)))

array([[0.63797193]])

### Cross product

For the vectors: $\vec u$ and $\vec v$, their cross product (or vector product) is another perpendicular vector (orthogonal) to both $\vec u$ and $\vec v$ with a direction given by the right-hand rule and a magnitude equal to the area of the parallelogram that the vectors span. It is represented as $\vec u \times \vec v$, $\vec u ∧ \vec v$, or $|u⟩⟨v|$ in Dirac notation:

$$ \vec u ∧ \vec v = |u⟩⟨v| = \|u\|_2\|v\|_2\sin{\theta}\vec n$$

In 3-dimensions, the cross product can be demonstrated by determinant:

$$  \vec u ∧ \vec v =\left|\begin{array}{}
    \hat{x} & \hat{y} & \hat{z}\\
    u_x & u_y & u_z  \\
    v_x & v_y & v_z \\
\end{array}\right|. $$
